export const ADD_BANNER_REQUEST = "ADD_BANNER_REQUEST";
export const ADD_BANNER_SUCCESS = "ADD_BANNER_SUCCESS";
export const ADD_BANNER_FAIL = "ADD_BANNER_FAIL";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";

export const FIND_ALL_BANNER_REQUEST = "FIND_ALL_BANNER_REQUEST";
export const FIND_ALL_BANNER_SUCCESS = "FIND_ALL_BANNER_SUCCESS";
export const FIND_ALL_BANNER_FAIL = "FIND_ALL_BANNER_FAIL";

export const FIND_ONE_BANNER_REQUEST = "FIND_ONE_BANNER_REQUEST";
export const FIND_ONE_BANNER_SUCCESS = "FIND_ONE_BANNER_SUCCESS";
export const FIND_ONE_BANNER_FAIL = "FIND_ONE_BANNER_FAIL";

export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAIL = "UPDATE_BANNER_FAIL";

export const BANNER_VISIBLE_REQUEST = "BANNER_VISIBLE_REQUEST";
export const BANNER_VISIBLE_SUCCESS = "BANNER_VISIBLE_SUCCESS";
export const BANNER_VISIBLE_FAIL = "BANNER_VISIBLE_FAIL";
